apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lpxn8np32-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lpxn8np32-nodejs 
  name: lpxn8np32-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lpxn8np32-nodejs 
