apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lpxn8np32-nodejs 
  janus-idp.io/tekton: lpxn8np32-nodejs
  backstage.io/kubernetes-id: lpxn8np32-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpxn8np32-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  